### PR TITLE
Add multiple bots found in the logs

### PR DESCRIPTION
**Pull request by fekir**

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks, CI is failing.

**Comment by fekir** [comment]
I've removed some bots (I'll eventually readd them in a separate PR), how should I handle, for example, following error?


````
ValueError: Pattern 'deadlinkchecker' is a subset of 'LinkChecker'                                                                                                    
````

It is not a subset as the casing is different, and they are different bots, so the url field should be different.

**Comment by monperrus** [comment]
that's lots of new bots, thanks. What was your strategy to identify them?

**Comment by fekir** [comment]
I've grepped for insensitive literal bot, spider and crawler after applying all your regexes

**Comment by monperrus** [comment]
simple and effective

**Comment by monperrus** [comment]
>  how should I handle, for example, following error?

the bot is already matched by the superset regexp,  so we're safe.

**Comment by fekir** [comment]
> > how should I handle, for example, following error?
> 
> the bot is already matched by the superset regexp, so we're safe.

Ah, I see, I should execute all regexes as case-insensitive

**Pull request merged**
