### PR TITLE
Added Pinterest bot

### PR DESCRIPTION
**Pull request by datafeedr**
Found this user agent `Pinterest/0.2 (+http://www.pinterest.com/bot.html)` in my logs.

### CODE REVIEW

**Comment by monperrus** [comment]
thanks. 
In case pinterest changes the URL (for instance to `https://help.pinterest.com/en/articles/about-pinterest-crawler-0`), what about a simpler pattern `Pinterest`?

**Comment by datafeedr** [comment]
Yeah, that would probably be simpler. Feel free to update the code. Thanks!

**Comment by monperrus** [comment]
thanks!

**Comment by cipater** [comment]
I believe `pinterest` is too generic a pattern. They have a web view in their iOS and Android clients that come in as `[Pinterest/iOS]` and `[Pinterest/Android]`.

So I'm getting false positives on these:

`Mozilla/5.0 (Linux; Android 8.0.0; SAMSUNG-SM-G935A Build/R16NW; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.110 Mobile Safari/537.36 [Pinterest/Android]`

`Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16B92 [Pinterest/iOS]`

**Comment by monperrus** [comment]
Would you see an alternative more precise pattern?

**Comment by monperrus** [comment]
Let's try: https://github.com/monperrus/crawler-user-agents/pull/155

**Pull request merged**
