### PR TITLE
Validate.py: case insensitive duplicate check

### PR DESCRIPTION
**Pull request by fallax**
I noticed that I was running into problems with the latest crawler-user-agents and realised that there were some duplicates that weren't being caught by validate.py as the patterns had different case (rather than having a single pattern matching both capitalisations).

I've updated crawler-user-agents.json to ensure that we're still passing the validation with this slightly more stringent check.

I am *not* a python person, so definitely improve my validate.py addition if there is a better way of doing this

### CODE REVIEW

**Comment by fallax** [comment]
I stepped away from my keyboard for a minute and then a better solution was immediately obvious:

```
    # check for duplicates with different capitalization
    pattern_counts = Counter(entry['pattern'].lower() for entry in json_data)
    for pattern, count in pattern_counts.most_common():
        if count > 1:
            raise ValueError('Pattern {!r} is duplicated {} times with different capitalization'
                             .format(pattern, count))
```

**Comment by monperrus** [comment]
thanks a lot for your contribution. could you add a test of the validation itself in `test_validation.py`? Thanks.

**Comment by fallax** [comment]
I've added the test_validation.py check.

**Comment by monperrus** [comment]
thanks a lot!

**Pull request merged**
