### PR TITLE
Fix too simple patterns

### PR DESCRIPTION
**Pull request by shimpeko**
retry for https://github.com/monperrus/crawler-user-agents/pull/111

I've removed commits without example.

### CODE REVIEW

**Comment by monperrus** [comment]
why do say they are too simple? you've seen collisions for all of them?

**Comment by jimdigriz** [comment]
https://github.com/monperrus/crawler-user-agents/commit/7377a8b81ee36339409374f9463f9a6bd4702515 mis-matches the following:
```
Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/5.0; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.0.30729)
```

**Comment by shimpeko** [comment]
> why do say they are too simple? you've seen collisions for all of them?

Yes. I put example UAs on each commit log.

**Comment by shimpeko** [comment]
I'd like you to accept at least fix for `LCC` 7377a8b . Which mis-matches many non-crawler UAs.

**Comment by monperrus** [comment]
Thanks a lot!

**Pull request merged**
