### PR TITLE
Make validation case sensitive

### PR DESCRIPTION
**Pull request by dan-blanchard**
This pulls out just the case sensitivity changes in #62

### CODE REVIEW

**Comment by monperrus** [comment]
I would keep the changes in crawler-user-agents.json, but not in the validation code. Nothing prevents you of using crawler-user-agents.json in a case-sensitive way. Correct?

**Comment by dan-blanchard** [comment]
> I would keep the changes in crawler-user-agents.json, but not in the validation code. Nothing prevents you of using crawler-user-agents.json in a case-sensitive way. Correct?

It makes very little sense to me that you would want the validation to be less strict. People could choose to use them in a case insensitive manner (and suffer the false-positive consequences that I've been mentioning), but the patterns themselves should match the instances in a case sensitive fashion by default. Why let people submit patterns that rely on case insensitivity and then do not function in many users code?

By defaulting to sensitivity in the validation script, you're just making sure that both use cases are supported.

Also, I don't think I can understate how many false positives using these in a case insensitive fashion will cause because of `Pinterest` being in the user agent for their mobile app, but `pinterest` being in their bot UA.

**Comment by monperrus** [comment]
you're probably right. since we now have an active community on crawler-user-agents, a case-change would likely be detected fast.

**Comment by dan-blanchard** [comment]
I rebased and fixed the failing test case here.

**Comment by monperrus** [comment]
thanks!

**Pull request merged**
