### PR TITLE
added WordPress crawler

### PR DESCRIPTION
**Pull request by petrokrupenia**

### CODE REVIEW

**Comment by petrokrupenia** [comment]
Have no idea. Are there some other details?

**Comment by monperrus** [comment]
See https://app.travis-ci.com/github/monperrus/crawler-user-agents/builds/266792708


```$ python3 validate.py

Traceback (most recent call last):

  File "/home/travis/build/monperrus/crawler-user-agents/validate.py", line 95, in <module>

    main()

  File "/home/travis/build/monperrus/crawler-user-agents/validate.py", line 55, in main

    raise ValueError('Pattern {!r} has an unescaped slash character'.format(pattern))

ValueError: Pattern 'WordPress/' has an unescaped slash character
```

**Comment by petrokrupenia** [comment]
added fix

**Comment by monperrus** [comment]
thanks!

"WordPress/X.X.X; https://example.com" is fake, do you have a real example? Which wordpress plugin sends this?

Thanks!

**Comment by petrokrupenia** [comment]
It is not a fake. WordPress has its own bot/crawler (not wordpress plugin). 

Our plugin tracks user agents for statistics, and one of the users noticed that there were too many posts from UA with such parameters: `WordPress/6.3. 1; https://usersdomain.com` (can't add real domain, privacy, etc.)

Also i found this: https://useragents.io/explore/platforms/unknown/maker/wordpress-org-b87

**Comment by monperrus** [comment]
ack, thanks for the additional info

**Comment by devicenull** [comment]
Hi @petrokrupenia , can you provide any references or links about where WordPress has a crawler built in?  I'm not able to find things (although there are a number of third party plugins that do it - but not the core WordPress)

**Pull request merged**
