### PR TITLE
Added user agents from Apify / crawlee-python fingerprint dataset

### PR DESCRIPTION
**Pull request by brentclark**
Added user agents from Apify / crawlee-python fingerprint dataset
Please consider adding.

### CODE REVIEW

**Comment by monperrus** [comment]
thanks for the contribution @brentclark 

the instances do not match the pattern, see CI failure.

What about removing them?

**Comment by rarous** [comment]
Apify/crawlee uses browser UAs and is never disclosed with its own UA string.

**Comment by monperrus** [comment]
how to detect them? using heuristics on HTTP headers?

**Comment by rarous** [comment]
They are using bayesian networks (see https://github.com/apify/fingerprint-suite/), I don't think it is worth the effort.

**Comment by monperrus** [comment]
then it's out of scope for crawler-user-agents, which is entirely based on UA.

**Comment by monperrus** [comment]
thanks @brentclark for the suggestion!

**Pull request closed without merging**
