### PR TITLE
WIP: Add check to validate patterns compatibility with re2 library

### PR DESCRIPTION
**Pull request by vetyy**

### CODE REVIEW

**Comment by monperrus** [comment]
The pattern seems accepted by re2 since this Travis is OK

**Comment by vetyy** [comment]
libre2-dev package is officially available only since ubuntu 16.04+

**Comment by monperrus** [comment]
why do you need libre2-dev since we can install re2 with pip?

**Comment by vetyy** [comment]
libre2-dev is actually this: https://github.com/google/re2/ - its C++ implementation of library,
every other language (including python) is basically just wrapper around this library so you need it in order to compile python re2 package

**Comment by monperrus** [comment]
I thought pip would download and compile the library on its own (I've seen this many times)

**Comment by vetyy** [comment]
unfortunately not :( you must install prerequisites upfront (more info here: https://pypi.python.org/pypi/re2/)

**Comment by monperrus** [comment]
closing this old failing PR, don't hesitate to reopen if appropriate

**Pull request closed without merging**
