### PR TITLE
add hatena scissors

### PR DESCRIPTION
**Pull request by Fale**

### CODE REVIEW

**Comment by Fale** [comment]
I've splitted Hatena.
From reading around it seems like there are many hatena bots doing different things.
I'm not sure if we want to distinguish them or if we want to merge them all together (but this would be different from what we are doing with other bots, like the many google bots

**Comment by monperrus** [comment]
Google/Googlebot is an exceptional monster. If Hatena is a family of small bots run by the same company, I have a slight preference for keeping them together.

**Comment by Fale** [comment]
Hatena is a small company (https://en.wikipedia.org/wiki/Hatena_(company)) and I agree that it probably does not make sense to have them splitted

**Comment by monperrus** [comment]
OK, we can close! Thanks for your proposal :-)

**Pull request closed without merging**
