### PR TITLE
Improve Python usage harness

### PR DESCRIPTION
**Pull request by jribbens**
The current Python usage harness:
* is very, very, very slow;
* matches the patterns case-insensitively, which is not what the other languages' harnesses do, and is not how the patterns appear to be intended to be used;
* is missing the `matching_crawlers()` function that the Go harness provides.

This patch fixes all these issues. In some simple tests, the updated `is_crawler()` function is well over a _hundred times_ faster than the current version.

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot for the contribution. Would you also be able to contribute with a test case run in CI? That would be awesome!

**Comment by jribbens** [comment]
Ok I've added some simple tests, updated `pyproject.toml` a bit (dev dependencies are now in it rather than a separate `requirements.txt`, and it defines a project homepage), and changed the CI workflow so it uses `pip install -e .[dev]` so that the test file can `import crawleruseragents` in order to test it.

**Comment by jribbens** [comment]
If you're interested, I also reworked the Python harness to be completely type-annotated and other fixes so it can be fully type-checked and linted with 'mypy --strict', 'ruff check' and 'ruff format': https://github.com/jribbens/crawler-user-agents/compare/master...jribbens:crawler-user-agents:full-typing

This involves considerably more changes to the code though, of course, and it means it's only compatible with Python 3.8 or later (not sure what version you were targeting previously).

**Comment by monperrus** [comment]
thanks a lot @jribbens

**Pull request merged**
