### PR TITLE
added scanbot

### PR DESCRIPTION
**Pull request by mattmarcum**

### CODE REVIEW

**Comment by mattmarcum** [comment]
Love this repo, I've added all the bots I saw in my logs that weren't already in this list.  Thanks!

**Comment by monperrus** [comment]
no trace of this one in my own logs. can you tell me about this bot? open-source or commercial?

**Comment by mattmarcum** [comment]
No idea - I just found it in my logs, I wonder if its this: http://crawler-and-email-scan-bot-software.7freedownload.com/

**Comment by monperrus** [comment]
it seems not enough notable to be included.

**Pull request closed without merging**
