### PR TITLE
Clean up validate.py

### PR DESCRIPTION
**Pull request by dan-blanchard**
I'm a Python guy, so I made `validate.py` more Pythonic. I also fixed some case sensitivity issues, because many of these patterns will match too much if you're using them insensitively—`pinterest` being a prime example.

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot.

Let's aim at aim at one PR per problem: 

* Regarding case-sensitivity, I'm not sure, because this makes the list more brittle to changes on the crawler side
* Regarding being pythonic, yeah! but one step after the other so that a the diff is small to understand, easy to discuss and it's easy to validate that the code is equivalent (since we don't test this validation code, only code review prevents regression)

**Comment by monperrus** [comment]
we should probably start with #63 before massive refactoring of validate.py

**Comment by dan-blanchard** [comment]
> Regarding case-sensitivity, I'm not sure, because this makes the list more brittle to changes on the crawler side

I agree it makes things slightly more brittle, but we could update things to be explicit when there are bits that need to be case sensitive. The number of false positives I had when using this list case insensitively was astounding because of all the Pinterest mobile app UAs that got picked up as bots.

I'll put out the case sensitivity changes and make a separate PR for them.

**Comment by dan-blanchard** [comment]
I'll rebase this after #66 and #65 are merged.

**Comment by dan-blanchard** [comment]
Okay, this is rebased and should be good to go.

**Comment by monperrus** [comment]
really well-done step-by-step work! thanks a lot!

**Pull request merged**
